language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - pip install pipenv
    - pipenv install --dev
    - pipenv shell

script:
    - pytest -v

notifications:
    email: false
