language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - pip install requests pytest slumber
    - python3 setup.py install

script:
    - pytest -v

notifications:
    email: false
